### ISSUE TITLE
Reader List is Not Showing

### ISSUE THREAD

**Issue by maq796113** [4i8/QuranBot#3]
**To Reproduce**

1. Go to '/play' command
2. See error

**Expected behavior**
I was expecting to see a list of Qaris

**Screenshots**

![image](https://github.com/4i8/QuranBot/assets/67544354/32a2400a-fe86-41cf-9217-395358b2e9b0)

**Desktop (please complete the following information):**

-   OS: Windows 11

**Comment by 4i8** [comment]
> **To Reproduce**
> 
> 1. Go to '/play' command
> 2. See error
> 
> **Expected behavior** I was expecting to see a list of Qaris
> 
> **Screenshots**
> 
> ![image](https://user-images.githubusercontent.com/67544354/279271086-32a2400a-fe86-41cf-9217-395358b2e9b0.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows 11

Alsalam Ealaykum, Mohammed. Inshallah, the bot will return in a few days. We are currently working on transferring it to another server, and we are actively working on it
