### ISSUE TITLE
offline , failing to load

### ISSUE THREAD

**Issue by McQueeen95** [4i8/QuranBot#4]
**Describe the bug**
failing to load the reader and surah

**To Reproduce**

1. Go to a room
2. type /play 
3. type part of the reader's name
4. See the error that is failing to load the reader's name

**Expected behavior**
gave me a list of the readers's names.

**Screenshots**

**Desktop (please complete the following information):**

-   OS: Windows  11
-   Browser: Edge
-   Version 22

![Screenshot 2023-12-28 234555](https://github.com/4i8/QuranBot/assets/90174812/8babb2d5-e690-45d8-bc6f-ab58228aaf14)

**Smartphone (please complete the following information):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**

**Comment by 4i8** [comment]
back to online✅✅
